### ISSUE TITLE
`db init` does not create any missing schemas

### ISSUE THREAD

**Issue by tjlevel12** [level12/keg#143]
Paraphrased from [slack](https://level12.slack.com/archives/C02DAPS3T/p1593190220025200):
> In keg, when you have the KEG_DB_DIALECT_OPTIONS['postgresql.schemas'] set, keg will create the schemas listed when you run your tests. When running `db init` I'm not seeing that behavior, it's telling me that my additional schemas don't exist while it's trying to run create_all.
Currently, `db init --clear` will create the schemas, but not simply `db init`.
I'd expect an init without clear to create the objects that don't exist.

**Comment by guruofgentoo** [comment]
Duplicates #40.
