### ISSUE TITLE
BaseView: difficult to know when a class is supposed to be exposed with a route

### ISSUE THREAD

**Issue by rsyring** [level12/keg#18]
``` python
class PayeeFormBaseView(FISBaseView):
    blueprint = admin
    def post(self, payee):
       ...

    def get(self):
        ...

class PayeeFormContract(PayeeFormBaseView):
    rule('/payee-forms/<int:payee_id>/contract', post=True)
    ....
```

The above doesn't work as expected.  It ends up not creating the route for `PayeeFormContract`.

**Comment by 3noch** [comment]
`rule` is really trippy. It breaks a lot of dev intuition. Can it be inherited? Is it meta? Is it changing my methods? Perhaps a better idiom would be a class decorator?

**Comment by guruofgentoo** [comment]
This is an old issue, and I can't reproduce the behavior. A view set up like the one above does generate a route.
