### ISSUE TITLE
Use pytest-cov 2.0 for combined coverage output

### ISSUE THREAD

**Issue by rsyring** [level12/keg#4]
On 03/23/2015 05:30 PM, Marc Schlaich wrote:

> Hey Randy,
> 
> in the upcoming pytest-cov 2.0 you can easily create different data files for each tox environment and automatically combine them at the end of the tox run. See here for an example project:
> https://github.com/schlamar/pytest-cov/tree/2.0/example-tox-project
> 
> Unfortunately, there is no release date yet as I'm pretty busy right now. However, the 2.0 branch should be quite stable, so you could give it a try.
> 
> Marc

**Comment by nZac** [comment]
pytest-cov 2 is being used, see https://github.com/level12/keg/blob/master/requirements/wheelhouse/pytest_cov-2.2.1-py2.py3-none-any.whl
