### ISSUE TITLE
Add post-response middleware

### ISSUE THREAD

**Issue by 3noch** [level12/keg#60]
There are many generic ways to inject code before a response is generated, but I can't find any way to insert a response "middleware" (i.e. a way to modify responses for a certain class hierarchy).

**Comment by rsyring** [comment]
This might help you modify a response: http://flask.pocoo.org/docs/0.12/api/#flask.request_finished

You can also create a method on the view class `pre_response` that will get called before the response is returned: https://github.com/level12/keg/blob/master/keg/web.py#L158

**Comment by 3noch** [comment]
Aha, I didn't notice thi `pre_respond` method. Can that *modify* the response?

**Comment by rsyring** [comment]
Yes, looks like the current method is in-place mutation.  

I'd take a PR to use a return value from `pre_response` if `not None` as the response, to support sending a completely different response object.
