### ISSUE TITLE
Enable pessimistic connections for SQLAlchemy

### ISSUE THREAD

**Issue by bladams** [level12/keg#73]
This could prevent unnecessary exceptions with very little performance penalty. This will need to wait until the release of SQLAlchemy 1.2

https://docs.sqlalchemy.org/en/latest/core/pooling.html#pool-disconnects-pessimistic

**Comment by rsyring** [comment]
Related to: https://github.com/level12/board-development/issues/7

Possibly blocked by: https://github.com/mitsuhiko/flask-sqlalchemy/issues/166

**Comment by bchopson** [comment]
Resolved by GH-113
