### ISSUE TITLE
Python 3.6 tests won't pass due to lack of pyodbc support

### ISSUE THREAD

**Issue by rsyring** [level12/keg#77]
Our docker container doesn't have Python dev installed and there are no pymssql wheels for 3.6, so pip install breaks.  

Example test run: https://circleci.com/gh/level12/keg/115

Options;

* Make a new release of pymssql, which would help everyone
* Update our docker container to have whatever is needed to be able to build pymssql

**Comment by guruofgentoo** [comment]
python-test-multi has been updated to support pyodbc instead. We should shift to that, to be able to remove the platform filter here.

**Comment by guruofgentoo** [comment]
Update: per #125 we're using pyodbc in appveyor, but it's still behind the platform filter. To bring that into Circle CI, we'll need to set up the mssql docker image.
