### ISSUE TITLE
Auto-reload dev server on change

### ISSUE THREAD

**Issue by nZac** [level12/keg#8]
It would be really helpful if `<app> develop run` would auto reload when a change is made in a file.

Maybe this already exists?

**Comment by rsyring** [comment]
If you are using a profile with debug enabled:

https://bitbucket.org/level12/keg/src/cff89f924abe3d4de14dbb377f2c5a4f9bf70b76/keg/config.py?at=default#cl-166

then it should be working:

https://bitbucket.org/level12/keg/src/cff89f924abe3d4de14dbb377f2c5a4f9bf70b76/keg/_flask_cli.py?at=default#cl-379
