### ISSUE TITLE
Incorrect usage of Flask's app context during testing

### ISSUE THREAD

**Issue by rsyring** [level12/keg#90]
Our `keg.testing:ContextManager` is designed to cache the application instance as well as the app context.  However, after reading [the Flask docs on app context](http://flask.pocoo.org/docs/0.12/appcontext/), it has become obvious that I'm using the app context wrong.  Despite it's name, it's not intended to have the same life cycle as the app instance.  It's intended to have a lifetime almost the same as the request context.

This is actually the underlying reason behind the bug I thought Flask-WTF had: https://github.com/lepture/flask-wtf/issues/301

It looks like some kind of pytest fixture support is what we really need in order to make the app instance available to our tests instead of relying on `flask.current_app`.

Some good ideas here:

https://github.com/pytest-dev/pytest-flask

**Comment by rsyring** [comment]
A lot of our apps assume an app context is going to be available in `setup_class()` and `setup` fixtures for things like entity usage.  However, my attempt to fix Keg for this issue breaks those assumptions and would require a lot of work from the app developers to fix their tests.  I've been hoping pytest would address this, but the issue hasn't received much attention.  There is, however, a plugin now available:

https://github.com/pytest-dev/pytest/issues/517#issuecomment-415547051

**Comment by rsyring** [comment]
I haven't read all of your comment above yet but I wanted to point out that I was planning on solving some of the problems with this by using app/db fixtures in the `setup_*()` methods.  Felt like a reasonably quick find/replace operation to update all our usages.  But, fixtures aren't supported in those methods currently and I got no where trying to get them to address it.  It is addressable, just needs some time: https://github.com/pytest-dev/pytest/issues/5289

Also, maybe that's not the best solution.

**Comment by guruofgentoo** [comment]
I'm ending up doing two things:
- Most of the setup weirdness can be handled by having an app context pushed for loading tests. I.e. a fixture is run at module setup time. Note this is after test gathering happens, so `flask.current_app` isn't available for mocking decorators, but at least the db session is available.
  - That's fairly similar to how an app runs in CLI or a celery task, where we have a context pushed
  - https://github.com/level12/keg-auth/compare/master...testing-app-context is a good example of the changes that would require in an app
- Second, and the larger drawback here that makes the test suite different from running the app in production: nothing is pushing an app context on each request.
  - flask-webtest is the lib that does all the flask stack setup for webtest, so it seems like that's where it should happen
  - My intent is to wrap https://github.com/level12/flask-webtest/blob/master/flask_webtest.py#L220 with an app context push, from the app used to create the client
  - In my testing with keg-auth (linked above, which is pretty similar to how we test apps), that solved all of the `flask.g`-related issues

**Comment by guruofgentoo** [comment]
Note, https://github.com/level12/flask-webtest/pull/18 is required for the current solution.
