### ISSUE TITLE
Add PingDB view

### ISSUE THREAD

**Issue by rsyring** [level12/keg#94]
Or maybe just make the current Ping view smart enough that if a DB is being used, to add the SQL call into the current ping.

Example: https://github.com/level12/agari-adm/commit/203445a57e69a3c716327a794f885fe4fdaecee3

**Comment by guruofgentoo** [comment]
Currently exists at https://github.com/level12/keg-app-cookiecutter/blob/master/%7B%7Bcookiecutter.project_dashed%7D%7D-src/%7B%7Bcookiecutter.project_namespace%7D%7D/views/public.py#L26.
